package com.example.maziyyah.light_touch.light_touch.models;

import java.util.UUID;

public class User {
    
    private String userId; // autogenerated userId
    private String username;
    private String name;
    private String password;
    private String email;
    private String deviceId; // pre-generated 
    private String pairedDeviceId; // reference to another user
    private Boolean isPaired;
    private String telegramChatId;
    private String telegramLinkCode;


    public User() {
    }

    
    public User(String username, String name, String email, String password, String deviceId) {
        this.userId = UUID.randomUUID().toString().substring(0, 10);
        this.username = username;
        this.name = name;
        this.email = email;
        this.password = password;
        this.deviceId = deviceId;
    }

    public User(String userId, String username, String name, String password, String email, String deviceId,
            String pairedDeviceId, Boolean isPaired) {
        this.userId = userId;
        this.username = username;
        this.name = name;
        this.password = password;
        this.email = email;
        this.deviceId = deviceId;
        this.pairedDeviceId = pairedDeviceId;
        this.isPaired = isPaired;
    }


    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }




    public String getDeviceId() {
        return deviceId;
    }



    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }



    public String getEmail() {
        return email;
    }



    public void setEmail(String email) {
        this.email = email;
    }



    public String getPairedDeviceId() {
        return pairedDeviceId;
    }



    public void setPairedDeviceId(String pairedDeviceId) {
        this.pairedDeviceId = pairedDeviceId;
    }



    public Boolean getIsPaired() {
        return isPaired;
    }



    public void setIsPaired(Boolean isPaired) {
        this.isPaired = isPaired;
    }


    public String getTelegramChatId() {
        return telegramChatId;
    }


    public void setTelegramChatId(String telegramChatId) {
        this.telegramChatId = telegramChatId;
    }


    public String getTelegramLinkCode() {
        return telegramLinkCode;
    }


    public void setTelegramLinkCode(String telegramLinkCode) {
        this.telegramLinkCode = telegramLinkCode;
    }

    

    

    
    

    

    

}
